on:
  workflow_dispatch

jobs:
- name: Azure Login
  uses: Azure/login@v1.4.6
  with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
    creds: # optional
    # ClientId of the Azure Service principal created.
    client-id: # optional
    # TenantId of the Azure Service principal created.
    tenant-id: # optional
    # Azure subscriptionId
    subscription-id: # optional
    # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
    enable-AzPSSession: azurecloud
    environment: azurecloud
    # Set this value to true to enable support for accessing tenants without subscriptions
    allow-no-subscriptions: # optional
    # Provide audience field for access-token. Default value is api://AzureADTokenExchange
    audience: # optional, default is api://AzureADTokenExchange
---    
- name: Deploy Azure Resource Manager (ARM) Template
  uses: Azure/arm-deploy@v1.0.9
  with:
    # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
    scope: resourcegroup
    # Override the Subscription Id set by Azure Login.
    subscriptionId: # optional
    # Specify the Id for the Management Group, only required for Management Group Deployments.
    managementGroupId: # optional
    # Provide the target region, only required for management Group or Subscription deployments.
    region: # optional
    # Provide the name of a resource group, only required for resource Group deployments.
    resourceGroupName: # optional
    # Specify the path or URL to the Azure Resource Manager template.
    template: 
    # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
    deploymentMode: incremental
    # Specifies the name of the resource group deployment to create.
    deploymentName: # optional
    # Supply deployment parameter values.
    parameters: # optional
    # Specify whether to fail the action if some data is written to stderr stream of az cli. Valid values are: true, false
    failOnStdErr: # optional, default is true
    # Specify any additional arguments for the deployment.
    additionalArguments: # optional
